/*
 * resource
 *
 * resource
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ResourceGet -
func ResourceGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ResourceIdGet -
func ResourceIdGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ResourcePost -
func ResourcePost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
