/*
 * resource
 *
 * resource
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// InfoGet -
func InfoGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
