/*
 * resource
 *
 * resource
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type ResourceResponseDto struct {
	Id string `json:"id"`

	Name string `json:"name"`

	MagicNumber int32 `json:"magicNumber,omitempty"`
}
