/*
 * resource
 *
 * resource
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

import (
	"github.com/stefnef/Flowingo/m/internal/api/http/dto"
	"net/http"

	"github.com/gin-gonic/gin"
)

// InfoGet -
func InfoGet(c *gin.Context) {
	var infoDto = dto.InfoDto{
		Text: "It work's all!",
	}
	c.JSON(http.StatusOK, infoDto)
}
