/*
 * resource
 *
 * resource
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	sw "github.com/stefnef/Flowingo/m/internal/api/http"
	"log"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
	_ = router.SetTrustedProxies(nil)

	log.Fatal(router.Run(":8080"))
}
