/*
 * resource
 *
 * resource
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	sw "github.com/stefnef/Flowingo/m/internal/api/http"
	"github.com/stefnef/Flowingo/m/internal/api/http/handler"
	"github.com/stefnef/Flowingo/m/internal/core/service"
	"log"
)

func main() {
	log.Printf("Server started")

	var infoHandler = handler.NewInfoHandler(service.NewInfoService())
	var resourceHandler = handler.NewResourceHandler(service.NewResourceService(nil))

	router := sw.NewRouter(infoHandler, resourceHandler)
	_ = router.SetTrustedProxies(nil)

	log.Fatal(router.Run(":8080"))
}
