/*
 * resource
 *
 * resource
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type ResourcePostDto struct {
	Name string `json:"name"`
}
