openapi: 3.0.3
info:
  title: resource
  description: resource
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'

tags:
  - name: info
    description: Server information
  - name: resource
    description: Operations on resource

paths:
  /resource:
    $ref: "./path/resource.yaml#/resource"

  /resource/{id}:
    $ref: "./path/resource.yaml#/resourceId"

  /info:
    get:
      tags:
        - info
      description: "Basic information"
      responses:
        200:
          $ref: "#/components/responses/infoResponse"

components:
  responses:
    infoResponse:
      description: "Information about service"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/infoDto"

  schemas:
    infoDto:
      type: object
      properties:
        text:
          type: string

  securitySchemes:
    bearerSecurity:
      type: http
      name: access_token
      in: header
      scheme: bearer
      bearerFormat: JWT
