openapi: 3.0.3
info:
  title: resource
  description: resource
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'

tags:
  - name: info
    description: Server information
  - name: resource
    description: Operations on resource

paths:
  /resource:
    get:
      tags:
        - resource
      description: Returns all resources
      responses:
        200:
          $ref: "./response/resource.yaml#/components/responses/resourceListResponse"

    post:
      tags:
        - resource
      description: Adds a new resource
      requestBody:
        $ref: "./request/resource.yaml#/components/requestBodies/resourcePostBody"
      responses:
        201:
          $ref: "./response/resource.yaml#/components/responses/resourceResponse"
      security:
        - bearerSecurity: []

  /resource/{id}:
    get:
      tags:
        - resource
      description: "Retrieve resource with given id"
      parameters:
        - $ref: "./parameters/parameters.yaml#/components/parameters/resourceId"
      responses:
        200:
          $ref: "./response/resource.yaml#/components/responses/resourceResponse"

  /info:
    get:
      tags:
        - info
      description: "Basic information"
      responses:
        200:
          $ref: "#/components/responses/infoResponse"

components:
  responses:
    infoResponse:
      description: "Information about service"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/infoDto"

  schemas:
    infoDto:
      type: object
      properties:
        text:
          type: string

  securitySchemes:
    bearerSecurity:
      type: http
      name: access_token
      in: header
      scheme: bearer
      bearerFormat: JWT
